### PR TITLE
fix 404

### PR DESCRIPTION
**Pull request by peter-peter-22**
add the standard vercel.json to the frontend that will return the page on all locations preventing 404 error when updating the page outside "/"

### CODE REVIEW

**Comment by peter-peter-22** [comment]
Hi, I am ✨✨✨.
Vercel has a problem with react pages that can be fixed by vercel.json.
I added it to the right folder.

**Comment by hegdeadithyak** [comment]
> Hi, I am ✨✨✨. Vercel has a problem with react pages that can be fixed by vercel.json. I added it to the right folder.

Thanks for the PR!

**Comment by hegdeadithyak** [comment]
Hey @Magyar-Peter-22 ,you just formatted the existing code I hope you know that and that routing error needs to be fixed in `frontend/Mainpage.tsx` if you need some help let me know.

**Comment by peter-peter-22** [comment]
I only added vercel.json to the frontend folder.
I did not touched anything else, as it is visible in my commit.

**Comment by peter-peter-22** [comment]
I only added vercel.json to the frontend folder.
I did not touched anything else, as it is visible in my commit.

Adithya Hegde Kota ***@***.***> ezt írta (időpont: 2024.
szept. 16., H, 4:50):

**Pull request merged**
